server:
  port: 3344
spring:
  application:
    name: hm-blog-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ai1045152332/springcloud-config.git
          username: ai1045152332
          password: 1045152332zjy
          # 缓存位置
          basedir: D:\gitproject2\hm-blog-parent\cache